name: "The chosen one"
on:
  pull_request_target:
    types: [opened, ready_for_review, reopened]

jobs:
  draw:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
    - uses: actions/checkout@v1
    - uses: uesteibar/reviewer-lottery@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
