# on:
#   push:
#     branches:
#       - master
#       - celo/1258/changelog
#     paths:
#       - CHANGELOG.md
#
# jobs:
#   publish:
#     runs-on: ubuntu-latest
#     name: 'Publish Changelog'
#     steps:
#       - name: Checkout docs
#         uses: actions/checkout@v3
#         with:
#           repository: cognitedata/doc.cognitedata.com
#
#       - name: Checkout proto
#         uses: actions/checkout@v3
#         with:
#           path: seismic-proto
#
#       - name: Commit changes
#         run: |
#           cp seismic-proto/CHANGELOG.md docs/dev/seismic_changelog.md
#           git checkout -b seismic-proto/changelog-updater-${{ GITHUB_RUN_NUMBER }}
#           git add docs/dev/seismic_changelog.md
#           git commit -m 'Bring in updates from seismic-proto changelog'
#           git push --set-upstream origin seismic-proto/changelog-updater-${{ GITHUB_RUN_NUMBER }}
#
#       - name: Create pull request
#         id: pr
#         uses: repo-sync/pull-request@v2
#         with:
#           source_branch: seismic-proto/changelog-updater
#           pr_title: Sync changes from seismic CHANGELOG
#           pr_body: '**Automated PR:**  Bring in updates to CHANGELOG.md from the [seismic-proto](https://github.com/cognitedata/seismic-proto/blob/master/CHANGELOG.md) repository'
#           destination_branch: master
#           # destination_repository: cognitedata/doc.cognitedata.com
#           destination_repository: cognitedata/hackathon-subsurface-ducks-in-a-row
#
#       - name: Echo PR link
#         run: echo PR created at ${{ steps.pr.outputs.pr_url }}

# on:
#   pull_request:
#     branches:
#       - master
#     paths:
#       - CHANGELOG.md
#
# jobs:
#   reminder:
#     runs-on: ubuntu-latest
#     name: Remind to update the docs
#     steps:
#       - uses: trstringer/manual-approval@v1
#         with:
#           secret: ${{ github.TOKEN }}
#           approvers: ${{ github.author }}

on:
  push:
    branches:
      - master
      - celo/1258/changelog
    paths:
      - CHANGELOG.md

jobs:
  publish:
    runs-on: ubuntu-latest
    name: 'Publish Changelog'
    env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      DOCS_PATH: /tmp/docs
      PR_BRANCH: seismic-proto/changelog-updater
    steps:
      - name: Add SSH key
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.GH_ACCESS_KEY }}"

      - name: Checkout docs
        run: |
          # git clone git@github.com:cognitedata/doc.cognitedata.com ${DOCS_PATH}
          git clone git@github.com:cognitedata/hackathon-subsurface-ducks-in-a-row ${DOCS_PATH}
          cd ${DOCS_PATH}
          git checkout -b ${PR_BRANCH}-${{ GITHUB_RUN_NUMBER }}

      - name: Checkout proto
        uses: actions/checkout@v3

      - name: Commit changes
        run: |
          # cp CHANGELOG.md ${DOCS_PATH}/docs/dev/seismic_changelog.md
          cp CHANGELOG.md ${DOCS_PATH}/seismic_changelog.md
          cd ${DOCS_PATH}
          # git add docs/dev/seismic_changelog.md
          git add seismic_changelog.md
          git commit -m 'Bring in updates from seismic-proto changelog'
          git push --set-upstream origin ${PR_BRANCH}-${{ GITHUB_RUN_NUMBER }}

      - name: Create pull request
        run: |
          cd ${DOCS_PATH}
          gh pr create \
            --title "Sync changes from seismic CHANGELOG" \
            --body '**Automated PR:**  Bring in updates to CHANGELOG.md from the [seismic-proto](https://github.com/cognitedata/seismic-proto/blob/master/CHANGELOG.md) repository' \
            --base master
